version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
    env_file:
      - .env
    networks:
      - app-network

  transactions:
    build:
      context: ./transactions
      dockerfile: Dockerfile
    expose: # Only expose internally to the Docker network
      - "8080"
    env_file:
      - .env
    networks:
      - app-network

  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    expose: # Only expose internally to the Docker network
      - "8081"
    env_file:
      - .env
    networks:
      - app-network

  reverse-proxy:
    build:
      context: ./reverse-proxy
      dockerfile: Dockerfile
    ports:
      - "5000:5000" # Nginx handles external traffic
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/conf.d/default.conf
    env_file:
      - .env
    networks:
      - app-network
    depends_on:
      - transactions
      - auth

networks:
  app-network:
    driver: bridge
