version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
    env_file:
      - .env
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - app-network
    depends_on:
      - frontend

  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    env_file:
      - .env
    networks:
      - app-network
    depends_on:
      - frontend

networks:
  app-network:
    driver: bridge
