CREATE TEMP TABLE temp_check AS
SELECT 1 FROM TRANSACTIONS LIMIT 1;

INSERT INTO TRANSACTIONS (AMOUNT)
SELECT 100.00
WHERE NOT EXISTS (SELECT 1 FROM temp_check);

INSERT INTO TRANSACTIONS (AMOUNT)
SELECT 200.00
WHERE NOT EXISTS (SELECT 1 FROM temp_check);

DROP TABLE temp_check;