-- Check if the TRANSACTIONS table is empty before inserting
INSERT INTO TRANSACTIONS (AMOUNT)
SELECT * FROM (
    SELECT 100.00 AS AMOUNT
    UNION ALL
    SELECT 200.00
) AS temp
WHERE NOT EXISTS (SELECT 1 FROM TRANSACTIONS);